### PR TITLE
Fix ignoring of E0 when tvbd search is used.

### PR DESCRIPTION
**Pull request by lars-a**

### CODE REVIEW

**Review by Maven85 — COMMENTED** [review]
Why the condition 'not settings.NO_E0_STRMS_EXPORT'?

**Comment by lars-a** [comment]
I thought it would be best, if the TVDB search also respected the "Do not export bonus episodes" setting.

**Comment by Maven85** [comment]
Ok, but what if
` not settings.NO_E0_STRMS_EXPORT = false` and `episode = 0`?

The condition is met and E0 is not ignored.

**Comment by lars-a** [comment]
In that case the User has not selected the "Do not export bonus episodes" setting and the episode would be exported anyway. So it is also OK to trigger the TVDB search for this episode.

**Comment by Maven85** [comment]
Then I just got it wrong. I thought E0 should always be ignored.

Then good to merge.

**Pull request merged**
